esphome:
  name: 8266-test
  friendly_name: 8266_test

esp8266:
  board: esp01_1m

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "WK/R0wKKfgPeqPEm8uDB+UTNUw1TUKvf78Si5Nv6PNY="

ota:
  - platform: esphome
    password: "a1b44e986246fd2da274885215859a7f"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "8266-Test Fallback Hotspot"
    password: "eAI3e8MvZr2n"

captive_portal:

switch:
  - platform: gpio
    name: "Living Room Dehumidifier"
    pin: GPIO5
