# ########################################################################
# simple configuration
# ########################################################################
esphome:
  name: esp32-hello-world-01
  friendly_name: esp32_hello_world_01

esp32:
  board: esp32dev
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "DGeIhuKBWS0upt+5Cr7yrEGh21sTYBLRUyTIR9Hxag8="

ota:
  - platform: esphome
    password: "b47b73b03aaea675dc375dc8494e458a"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Esp32-Hello-World-01"
    password: "MBTpi9vBZITj"

captive_portal:

switch:
  - platform: gpio
    name: "Living Room Dehumidifier"
    pin: GPIO5

